on:
  workflow_dispatch:
  schedule:
  - cron: "0 20 * * *"
#  push:


jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eco4cast/rocker-neon4cast
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install R packages
        run: R -e 'source("install.R")' 
# Point to the right path, run the right Rscript command
      - name: Run automatic prediction file (temp_lm)
        run: Rscript ./Generate forecasts/temp_lm/forecast_model.R
      - name: Run automatic prediction file (temp_lm_all_sites)
        run: Rscript ./Generate forecasts/temp_lm_all_sites/forecast_model.R
